# Generated by Django 5.0.6 on 2024-06-11 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_data_task_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
